- id: datadog-metrics
  name: Datadog Metrics Hook
  uses: ./.github/workflows/retrieve-secrets.yaml
  description: A pre-commit hook to send logs and metrics to DataDog
  entry: ./run_datadog_metrics.bat
  language: script
