name: Retrieve Secrets

on:
  workflow_dispatch:

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Export Secrets
        run: |
          echo "API_GATEWAY_URL=${{ secrets.API_GATEWAY_URL }}" >> $GITHUB_ENV
          echo "X_PRECOMMIT_AUTH=${{ secrets.X_PRECOMMIT_AUTH }}" >> $GITHUB_ENV
